[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "ninja; sys_platform != 'win32'",
    "cmake>=3.12",
	"PyQt5>=5.15.2",
	"PyQt5-sip>=12.8.1",
	"numpy==1.19.3",
]
build-backend = "setuptools.build_meta"
